CREATE TABLE IF NOT EXISTS usuario_area (
    id_usuario_area INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_area VARCHAR(255) NOT NULL,
    activo INT DEFAULT 1,
    creado_por INT,
    creado_el DATE,
    actualizado_por INT,
    actualizado_el DATE
);

CREATE TABLE IF NOT EXISTS usuario_facultad (
    id_usuario_facultad INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_facultad VARCHAR(255) NOT NULL,
    activo INT DEFAULT 1,
    creado_por INT,
    creado_el DATE,
    actualizado_por INT,
    actualizado_el DATE
);

CREATE TABLE IF NOT EXISTS usuario_puesto (
    id_usuario_puesto INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_puesto VARCHAR(255) NOT NULL,
    activo INT DEFAULT 1,
    creado_por INT,
    creado_el DATE,
    actualizado_por INT,
    actualizado_el DATE
);

CREATE TABLE IF NOT EXISTS usuario_rol (
    id_usuario_rol INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_rol VARCHAR(255) NOT NULL,
    activo INT DEFAULT 1,
    creado_por INT,
    creado_el DATE,
    actualizado_por INT,
    actualizado_el DATE
);

CREATE TABLE IF NOT EXISTS usuario (
    id_usuario INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_rol_usuario INT,
    nombre VARCHAR(255) NOT NULL,
    apellido_paterno VARCHAR(255),
    apellido_materno VARCHAR(255),
    correo VARCHAR(255) UNIQUE,
    contrasena VARCHAR(255),
    telefono_fijo VARCHAR(50),
    telefono_contacto VARCHAR(50),
    imagen_usuario VARCHAR(255),
    facultad_usuario VARCHAR(255),
    area_usuario VARCHAR(255),
    puesto_usuario VARCHAR(255),
    activo INT DEFAULT 1,
    creado_por INT,
    creado_el DATE,
    actualizado_por INT,
    actualizado_el DATE
);

CREATE TABLE IF NOT EXISTS login_historial (
    id_login_historial INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario INT,
    creado_por INT,
    creado_el TIMESTAMP,
    actualizado_por INT,
    actualizado_el TIMESTAMP,
    FOREIGN KEY (id_usuario) REFERENCES usuario(id_usuario)
);

CREATE TABLE IF NOT EXISTS ponente_tipo (
    id_tipo_ponente INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_tipo_ponente VARCHAR(255) NOT NULL,
    activo INT DEFAULT 1,
    creado_por INT,
    creado_el DATE,
    actualizado_por INT,
    actualizado_el DATE
);

CREATE TABLE IF NOT EXISTS ponente (
    id_ponente INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_ponente VARCHAR(255) NOT NULL,
    grado_ponente VARCHAR(255),
    tipo_ponente INT,
    activo INT DEFAULT 1,
    creado_por INT,
    creado_el DATE,
    actualizado_por INT,
    actualizado_el DATE,
    FOREIGN KEY (tipo_ponente) REFERENCES ponente_tipo(id_tipo_ponente)
);

CREATE TABLE IF NOT EXISTS ponente_semblanza (
    id_semblanza INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_ponente INT,
    nombre_archivo VARCHAR(255),
    ruta_archivo VARCHAR(255),
    activo INT DEFAULT 1,
    creado_por INT,
    creado_el DATE,
    actualizado_por INT,
    actualizado_el DATE,
    FOREIGN KEY (id_ponente) REFERENCES ponente(id_ponente)
);

CREATE TABLE IF NOT EXISTS recinto (
    id_recinto INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR(255) NOT NULL,
    ubicacion VARCHAR(255),
    edificio VARCHAR(255),
    capacidad INT,
    activo INT DEFAULT 1,
    creado_por INT,
    creado_el DATE,
    actualizado_por INT,
    actualizado_el DATE
);

CREATE TABLE IF NOT EXISTS recinto_equipamiento_catalogo (
    id_equipamiento INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_equipamiento VARCHAR(255) NOT NULL,
    descripcion_equipamiento VARCHAR(255),
    activo INT DEFAULT 1,
    creado_por INT,
    creado_el DATE,
    actualizado_por INT,
    actualizado_el DATE
);

CREATE TABLE IF NOT EXISTS recinto_equipamiento (
    id_recinto_equipamiento INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_recinto INT,
    id_equipamiento INT,
    activo INT DEFAULT 1,
    creado_por INT,
    creado_el DATE,
    actualizado_por INT,
    actualizado_el DATE,
    FOREIGN KEY (id_recinto) REFERENCES recinto(id_recinto),
    FOREIGN KEY (id_equipamiento) REFERENCES recinto_equipamiento_catalogo(id_equipamiento)
);

CREATE TABLE IF NOT EXISTS recinto_imagen (
    id_recinto_imagen INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_recinto INT,
    ruta_imagen VARCHAR(255),
    nombre_archivo VARCHAR(255),
    tamanio_archivo INT,
    activo INT DEFAULT 1,
    creado_por INT,
    creado_el DATE,
    actualizado_por INT,
    actualizado_el DATE,
    FOREIGN KEY (id_recinto) REFERENCES recinto(id_recinto)
);

CREATE TABLE IF NOT EXISTS recursos_area (
    id_area INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_area VARCHAR(255),
    ubicacion_area VARCHAR(255),
    responsable_area VARCHAR(255),
    correo_contacto VARCHAR(255),
    numero_contacto VARCHAR(50),
    activo INT DEFAULT 1,
    creado_por INT,
    creado_el DATE,
    actualizado_por INT,
    actualizado_el DATE
);

CREATE TABLE IF NOT EXISTS recursos_catalogo (
    id_recurso INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_recurso VARCHAR(255),
    descripcion_recurso VARCHAR(255),
    activo INT DEFAULT 1,
    creado_por INT,
    creado_el DATE,
    actualizado_por INT,
    actualizado_el DATE
);

CREATE TABLE IF NOT EXISTS reservacion_tipo_evento (
    id_tipo_evento INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_tipo_evento VARCHAR(255),
    descripcion_tipo_evento VARCHAR(255),
    activo INT DEFAULT 1,
    creado_por INT,
    creado_el DATE,
    actualizado_por INT,
    actualizado_el DATE
);

CREATE TABLE IF NOT EXISTS reservacion (
    id_reservacion INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_recinto INT,
    id_solicitante INT,
    fecha_reservacion DATE,
    hora_inicio TIME,
    hora_termino TIME,
    activo INT DEFAULT 1,
    creado_por INT,
    creado_el DATE,
    actualizado_por INT,
    actualizado_el DATE,
    FOREIGN KEY (id_recinto) REFERENCES recinto(id_recinto),
    FOREIGN KEY (id_solicitante) REFERENCES usuario(id_usuario)
);

CREATE TABLE IF NOT EXISTS recursos_reservacion (
    id_recurso_reservacion INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_recurso INT,
    id_reservacion INT,
    cantidad_asignada INT,
    activo INT DEFAULT 1,
    creado_por INT,
    creado_el DATE,
    actualizado_por INT,
    actualizado_el DATE,
    FOREIGN KEY (id_recurso) REFERENCES recursos_catalogo(id_recurso),
    FOREIGN KEY (id_reservacion) REFERENCES reservacion(id_reservacion)
);

CREATE TABLE IF NOT EXISTS reservacion_status (
    id_status INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_status VARCHAR(255),
    color_status VARCHAR(10),
    activo INT DEFAULT 1,
    creado_por INT,
    creado_el DATE,
    actualizado_por INT,
    actualizado_el DATE
);

CREATE TABLE IF NOT EXISTS reservacion_horas_disponibles (
    id_hora INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    hora TIME,
    activo INT DEFAULT 1,
    creado_por INT,
    creado_el DATE,
    actualizado_por INT,
    actualizado_el DATE
);

CREATE TABLE IF NOT EXISTS reservacion_origen (
    id_origen INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_origen VARCHAR(255),
    activo INT DEFAULT 1,
    creado_por INT,
    creado_el DATE,
    actualizado_por INT,
    actualizado_el DATE
);

CREATE TABLE IF NOT EXISTS semestre (
    id_semestre INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_semestre VARCHAR(50),
    anio_semestre VARCHAR(10),
    inicio_actividades DATE,
    fin_actividades DATE,
    activo INT DEFAULT 1,
    creado_por INT,
    creado_el DATE,
    actualizado_por INT,
    actualizado_el DATE
);

CREATE TABLE IF NOT EXISTS semestre_tipo_evento (
    id_semestre_tipo INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_tipo_evento VARCHAR(255),
    color_evento VARCHAR(10),
    activo INT DEFAULT 1,
    creado_por INT,
    creado_el DATE,
    actualizado_por INT,
    actualizado_el DATE
);

CREATE TABLE IF NOT EXISTS semestre_eventos (
    id_semestre_evento INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_semestre INT,
    id_tipo_evento INT,
    dia_evento DATE,
    activo INT DEFAULT 1,
    creado_por INT,
    creado_el DATE,
    actualizado_por INT,
    actualizado_el DATE,
    FOREIGN KEY (id_semestre) REFERENCES semestre(id_semestre),
    FOREIGN KEY (id_tipo_evento) REFERENCES reservacion_tipo_evento(id_tipo_evento)
);

